
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Configuration pour l'environnement local et production
const isLocalDevelopment = window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1';

const SUPABASE_URL = isLocalDevelopment 
  ? "http://127.0.0.1:54321"  // URL locale Supabase
  : "https://zjntkcgwzlmmgwtuxnjq.supabase.co";  // URL production

const SUPABASE_PUBLISHABLE_KEY = isLocalDevelopment
  ? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZmVyZW5jZS1pZCIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNjQ5Nzc5MjAwfQ.ta6J4fJ2sxDKzKXEH4IDrb3nkU06WhEHRJ8Myk_J8Ws"  // Clé anon locale par défaut
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbnRrY2d3emxtbWd3dHV4bmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIxNzgsImV4cCI6MjA2NTQ5ODE3OH0.rDPmlG9ah3UUkUbEzF8ryn6oa5h0VQ6c88P19JIH3aQ";  // Clé anon production

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
