// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjntkcgwzlmmgwtuxnjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqbnRrY2d3emxtbWd3dHV4bmpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjIxNzgsImV4cCI6MjA2NTQ5ODE3OH0.rDPmlG9ah3UUkUbEzF8ryn6oa5h0VQ6c88P19JIH3aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);